<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class parentstudentModel extends Model
{
    protected $table = "parent_student";
    protected $fillable = [
        'student_idcard_p',
        'prename_f',
        'name_f',
        'name_cen_f',
        'surname_f',
        'id_father',
        'type_card_f',
        'age_f',
        'bloodgroup_f',
        'job_f',
        'salary_f',
        'tel_f',
        'house_number_f',
        'group_f',
        'village_f',
        'alley_f',
        'street_f',
        'subdistrict_f',
        'district_f',
        'province_f',
        'post_f',
        'prename_m',
        'name_m',
        'name_cen_m',
        'surname_m',
        'id_mother',
        'type_card_m',
        'age_m',
        'bloodgroup_m',
        'job_m',
        'salary_m',
        'tel_m',
        'house_number_m',
        'group_m',
        'village_m',
        'alley_m',
        'street_m',
        'subdistrict_m',
        'district_m',
        'province_m',
        'post_m',
        'parent',
        'prename_p',
        'name_p',
        'name_cen_p',
        'surname_p',
        'id_parent',
        'type_card_p',
        'age_p',
        'bloodgroup_p',
        'job_p',
        'salary_p',
        'tel_p',
        'house_number_p',
        'group_p',
        'village_p',
        'alley_p',
        'street_p',
        'subdistrict_p',
        'district_p',
        'province_p',
        'post_p',
        'status_parent',
        'student_parent',
        'no_blood',
        'no_brother',
        'no_son',
        'no_sister',
        'no_son2',
        'no_parent',
        'no_study',
        'no_job',
        'no_house',
        'student_job',
        'student_money',
        'parent_money',
        'parent_total',
        'parent_house',
        'job_study',
        'job_detail',
        'total_study'
    ];
}
